name: coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  coverage:
    runs-on: windows-latest

    strategy:
      matrix:
        include:
          - branch: development
            tag: DEVELOPMENT-SNAPSHOT-2026-05-04-a

    steps:
      - uses: compnerd/gha-setup-swift@main
        with:
          tag: ${{ matrix.tag }}
          branch: ${{ matrix.branch }}

      - uses: actions/checkout@v7.0.0
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v --enable-code-coverage
      - name: Process Coverage Information
        run: |
          $bin = swift build --show-bin-path
          $objects = Get-ChildItem "$bin" -Include *-test-runner.exe,*Tests.dll -Recurse `
                   | ForEach-Object { '-object'; $_.FullName }
          llvm-cov export -format lcov -ignore-filename-regex '\.build[\\/]' -instr-profile "$bin\codecov\default.profdata" @objects | Set-Content -Encoding ascii -Path coverage.lcov
          $ws = $env:GITHUB_WORKSPACE
          (Get-Content coverage.lcov) `
            | ForEach-Object { $_ -replace [regex]::Escape("$ws\"), '' -replace [regex]::Escape("$ws/"), '' } `
            | ForEach-Object { $_ -replace '\\', '/' } `
            | Set-Content -Encoding ascii coverage.lcov
      - uses: codecov/codecov-action@v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.lcov
