name: windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  windows:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - branch: swift-5.5-release
            tag: 5.5-RELEASE

          - branch: swift-5.6.2-release
            tag: 5.6.2-RELEASE

          - branch: swift-5.7-branch
            tag: 5.7-DEVELOPMENT-SNAPSHOT-2022-06-04-a

          - branch: development
            tag: DEVELOPMENT-SNAPSHOT-2022-06-08-a

    steps:
      - uses: compnerd/gha-setup-swift@main
        with:
          tag: ${{ matrix.tag }}
          branch: ${{ matrix.branch }}

      - uses: actions/checkout@v2
      - name: Build
        run: swift build -v
        env:
          AR: llvm-ar
      - name: Run tests
        run: swift test -v
